imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@BlogCoreBundle/Resources/config/services.yml" }
    - { resource: "@BlogBlogBundle/Resources/config/services.yml" }
    - { resource: "@BlogBlogBundle/Resources/config/Form/contact.yml" }
    - { resource: "@BlogBlogBundle/Resources/config/Form/emailme.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: session.handler.native_file
        save_path: "%kernel.root_dir%/sessions"
#    fragments:       ~
    fragments: { path: /_fragment } # @see the Symfony FragmentListener
    http_method_override: true
    esi: { enabled: true } # To use ESI tags in Twig templates

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
#        default_entity_manager: blog_em
#        entity_managers:
#            blog_em:
#                connection: default
#                mappings:
#                    BlogUserBundle:  ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    encryption: "%mailer_encryption%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm #decommenter cette ligne lorsque le site sera mis en production. Puis mettre en commentaire la meme ligne du fichier config_dev.yml
    firewall_name: main
    user_class: Blog\BlogBundle\Entity\User
#    registration:
#        form:
#            type: blog_userbundle_userType
#        confirmation:
#            enabled:    true
#            from_email:
#                address:        noreply@getyouraffair.com
#                sender_name:    Get Your Affair
#            template:   BlogBlogBundle:Mail:registrationEmail.html.twig
    resetting:
        email:
            from_email:
                address:        noreply@getyouraffair.com
                sender_name:    Get Your Affair
            template: ECOUserBundle:Users:resetting.email.html.twig

#    change_password:
#        form:
#            type: me_user_change_password
#            template: ECOUserBundle:Users:resetting.email.html.twig

    from_email:
        address:        noreply@getyouraffair.com
        sender_name:    Get Your Affair

    service:
        mailer: fos_user.mailer.twig_swift

fos_comment:
    db_driver: orm
    class:
        model:
            comment: Blog\BlogBundle\Entity\Comment\Comment
            thread: Blog\BlogBundle\Entity\Comment\Thread
            vote: Blog\BlogBundle\Entity\Comment\Vote
    service:
#        markup: your_markup_service
        sorting:
            default: date_asc

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
    bundles: [ 'FOSCommentBundle', 'BlogBlogBundle' ]

fm_elfinder:
    instances:
        ckeditor:
            locale:           %locale%
            editor:           ckeditor
            fullscreen:       false
            include_assets:   true
            connector:
                debug:        false
                roots:
                    uploads:
                        driver:           LocalFileSystem
                        path:             uploadsf
                        upload_allow:     ['image/png', 'image/jpg', 'image/jpeg', 'image/gif', 'application/zip', 'audio/mpeg', 'text/csv', 'video/mp4', 'video/webm', 'application/pdf']
                        upload_deny:      ['all']
                        upload_max_size:  8M
    assets_path: /web/assets

ivory_ck_editor:
    default_config:    my_custom_config
    configs:
        my_custom_config:
            toolbar:                    full
            uiColor:                    #"#000000"
            height:                    '500px'
            width:                     '1000px'
            filebrowserBrowseRoute:     blog_blog_me_contacter
            filebrowserUploadUrl:     'http://127.0.0.1:5050/tchoulom/web/app_dev.php/'
            filebrowserBrowseRouteParameters:
                instance: ckeditor
            extraPlugins:               'pbckcode'
            pbckcode:                   { highlighter : 'HIGHLIGHT', tab_size : '4', theme : 'github',  modes :  [['Text', 'text'],['HTML', 'html'], ['CSS', 'css'], ['PHP', 'php'], ['JS', 'javascript'], ['YAML', 'yaml'], ['JSON', 'json'], ['SQL', 'sql'], ['Bash', 'bash']], js : "https://cdn.jsdelivr.net//ace/1.1.4/noconflict/" }
    plugins:
        video:
            path:                       '/bundles/blogblog/ckeditor/video/'
            filename:                   'plugin.js'
        pbckcode:
            path:                       '/bundles/blogblog/ckeditor/pbckcode/'
            filename:                   'plugin.js'
        uploadimage:
            path:     "/bundles/ivoryckeditor/plugins/uploadimage/"
            filename: "plugin.js"