# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Blog\BlogBundle\Entity\User: sha512

    # http://symfony.com/doc/current/book/security.html#hierarchical-roles
    role_hierarchy:
        ROLE_USER: [ROLE_ALLOWED_TO_SWITCH]
        ROLE_AUTHOR: [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]
        ROLE_ADMIN: [ROLE_USER, ROLE_AUTHOR, ROLE_ALLOWED_TO_SWITCH]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_AUTHOR, ROLE_USER, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
#        in_memory:
#            memory: ~
        main:
            id: fos_user.user_provider.username_email  # Se connecter avec son username ou son email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:  ^/
            anonymous: true
            provider: main
            form_login: # On définit notre méthode d'authentification :: login_path: eco_core_homepage est l entree du routing pour l acces a la page de login
                login_path: user_login
                check_path: fos_user_security_check
                always_use_default_target_path: true
                default_target_path: blog_core_home_index
                #default_target_path: eco_core_homepage est l entree du routing pour la redirection apres authentification via FOSUserBundle. FOSUserBundle redirige vers vette entree du routing apres authentification
            logout:
                path: fos_user_security_logout
                target: blog_core_home_index
                #target: eco_core_homepage: eco_core_homepage est l entree du routing pour la redirection apres deconnection via FOSUserBundle. FOSUserBundle redirige vers vette entree du routing apres deconnection
            remember_me: # On active la possibilité du Se souvenir
                key: %secret%
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER

#        main:
#            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
         - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/inscription, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^^/(css|js), roles: IS_AUTHENTICATED_ANONYMOUSLY }
#         - { path: ^/cours, roles: ROLE_USER }